package kojispawn;

import java.nio.file.Path;

import kojispawn.command.Command;
import kojispawn.command.CommandType;
import kojispawn.command.Parser;
import kojispawn.exception.KojisPawnException;
import kojispawn.storage.Storage;
import kojispawn.task.Task;
import kojispawn.task.TaskList;
import kojispawn.ui.Ui;

/**
 * Coordinates input parsing, task management, and user interaction.
 */
public class KojisPawn {
    private final Parser parser;
    private final Storage storage;
    private final TaskList tasks;
    private final Ui ui;
    private CommandType lastCommandType = CommandType.UNKNOWN;
    private boolean isExitRequested;

    /**
     * Creates the chatbot and loads any tasks saved in the default data file.
     *
     * @throws KojisPawnException If the task data cannot be loaded.
     */
    public KojisPawn() throws KojisPawnException {
        this(Path.of("data", "kojispawn.txt"));
    }

    KojisPawn(Path dataFile) throws KojisPawnException {
        this.parser = new Parser();
        this.storage = new Storage(dataFile);
        this.tasks = new TaskList(storage.load());
        this.ui = new Ui();
    }

    /**
     * Starts Koji's Pawn.
     *
     * @param args Command-line arguments, which are not used.
     * @throws KojisPawnException If the task data cannot be loaded.
     */
    public static void main(String[] args) throws KojisPawnException {
        new KojisPawn().run();
    }

    /**
     * Runs the chatbot until the user enters the {@code bye} command.
     */
    public void run() {
        ui.showGreeting();
        while (!isExitRequested) {
            ui.showResponse(getResponse(ui.readCommand()));
        }

        ui.close();
    }

    /**
     * Parses and executes one command for either the console or GUI.
     *
     * @param input Command entered by the user.
     * @return Response generated by Koji's Pawn.
     */
    public String getResponse(String input) {
        try {
            Command command = parser.parse(input);
            lastCommandType = command.getType();
            return execute(command);
        } catch (KojisPawnException exception) {
            lastCommandType = CommandType.UNKNOWN;
            return exception.getMessage();
        }
    }

    /**
     * Returns the type of the most recently processed command.
     *
     * @return Most recent command type, or {@link CommandType#UNKNOWN} after an error.
     */
    public CommandType getLastCommandType() {
        return lastCommandType;
    }

    /**
     * Returns whether the user has entered the {@code bye} command.
     *
     * @return {@code true} when the application should exit.
     */
    public boolean isExitRequested() {
        return isExitRequested;
    }

    /**
     * Executes a validated command.
     *
     * @param command Command returned by the parser.
     * @return Response describing the result.
     * @throws KojisPawnException If a task number is outside the list.
     */
    private String execute(Command command) throws KojisPawnException {
        return switch (command.getType()) {
            case TODO, DEADLINE, EVENT -> addTask(command.getTask());
            case LIST -> ui.formatTaskList(tasks.getTasks());
            case MARK -> markTask(command.getTaskNumber());
            case UNMARK -> unmarkTask(command.getTaskNumber());
            case DELETE -> deleteTask(command.getTaskNumber());
            case ON -> ui.formatTasksOnDate(tasks.findOn(command.getDate()), command.getDate());
            case FIND -> ui.formatMatchingTasks(tasks.find(command.getKeyword()));
            case BYE -> requestExit();
            case UNKNOWN -> throw new AssertionError("Parser returned an unknown command");
        };
    }

    /**
     * Adds a task, saves the updated task list, and formats the response.
     *
     * @param task Task to add.
     * @return Response describing the added task.
     * @throws KojisPawnException If the updated task list cannot be saved.
     */
    private String addTask(Task task) throws KojisPawnException {
        tasks.add(task);
        storage.save(tasks);
        return ui.formatTaskAdded(task, tasks.size());
    }

    /**
     * Marks a task, saves the updated task list, and formats the response.
     *
     * @param taskNumber One-based number of the task to mark.
     * @return Response describing the marked task.
     * @throws KojisPawnException If the task number is invalid or the task list cannot be saved.
     */
    private String markTask(int taskNumber) throws KojisPawnException {
        Task markedTask = tasks.mark(taskNumber);
        storage.save(tasks);
        return ui.formatTaskMarked(markedTask);
    }

    /**
     * Unmarks a task, saves the updated task list, and formats the response.
     *
     * @param taskNumber One-based number of the task to unmark.
     * @return Response describing the unmarked task.
     * @throws KojisPawnException If the task number is invalid or the task list cannot be saved.
     */
    private String unmarkTask(int taskNumber) throws KojisPawnException {
        Task unmarkedTask = tasks.unmark(taskNumber);
        storage.save(tasks);
        return ui.formatTaskUnmarked(unmarkedTask);
    }

    /**
     * Deletes a task, saves the updated task list, and formats the response.
     *
     * @param taskNumber One-based number of the task to delete.
     * @return Response describing the deleted task.
     * @throws KojisPawnException If the task number is invalid or the task list cannot be saved.
     */
    private String deleteTask(int taskNumber) throws KojisPawnException {
        Task deletedTask = tasks.delete(taskNumber);
        storage.save(tasks);
        return ui.formatTaskDeleted(deletedTask, tasks.size());
    }

    /**
     * Records that the application should exit and returns the farewell response.
     *
     * @return Farewell response.
     */
    private String requestExit() {
        isExitRequested = true;
        return ui.getExitMessage();
    }
}
