package kojispawn;

import java.nio.file.Path;
import java.time.LocalDate;

import kojispawn.command.Command;
import kojispawn.command.CommandType;
import kojispawn.command.Parser;
import kojispawn.exception.KojisPawnException;
import kojispawn.storage.Storage;
import kojispawn.task.Task;
import kojispawn.task.TaskList;
import kojispawn.ui.Ui;

/**
 * Coordinates input parsing, task management, and user interaction.
 */
public class KojisPawn {
    private final Parser parser;
    private final Storage storage;
    private final TaskList tasks;
    private final Ui ui;
    private CommandType lastCommandType = CommandType.UNKNOWN;
    private TaskList undoSnapshot;
    private boolean isExitRequested;

    /**
     * Creates the chatbot and loads any tasks saved in the default data file.
     *
     * @throws KojisPawnException If the task data cannot be loaded.
     */
    public KojisPawn() throws KojisPawnException {
        this(Path.of("data", "kojispawn.txt"));
    }

    KojisPawn(Path dataFile) throws KojisPawnException {
        this.parser = new Parser();
        this.storage = new Storage(dataFile);
        this.tasks = new TaskList(storage.load());
        this.ui = new Ui();
    }

    /**
     * Starts Koji's Pawn.
     *
     * @param args Command-line arguments, which are not used.
     * @throws KojisPawnException If the task data cannot be loaded.
     */
    public static void main(String[] args) throws KojisPawnException {
        new KojisPawn().run();
    }

    /**
     * Runs the chatbot until the user enters the {@code bye} command.
     */
    public void run() {
        ui.showGreeting();
        while (!isExitRequested) {
            ui.showResponse(getResponse(ui.readCommand()));
        }

        ui.close();
    }

    /**
     * Parses and executes one command for either the console or GUI.
     *
     * @param input Command entered by the user.
     * @return Response generated by Koji's Pawn.
     */
    public String getResponse(String input) {
        try {
            Command command = parser.parse(input);
            lastCommandType = command.getType();
            return execute(command);
        } catch (KojisPawnException exception) {
            lastCommandType = CommandType.UNKNOWN;
            return exception.getMessage();
        }
    }

    /**
     * Returns the type of the most recently processed command.
     *
     * @return Most recent command type, or {@link CommandType#UNKNOWN} after an error.
     */
    public CommandType getLastCommandType() {
        return lastCommandType;
    }

    /**
     * Returns whether the user has entered the {@code bye} command.
     *
     * @return {@code true} when the application should exit.
     */
    public boolean isExitRequested() {
        return isExitRequested;
    }

    /**
     * Executes a validated command.
     *
     * @param command Command returned by the parser.
     * @return Response describing the result.
     * @throws KojisPawnException If a task number is outside the list.
     */
    private String execute(Command command) throws KojisPawnException {
        assert command != null : "Command to execute must not be null";

        return switch (command.getType()) {
            case TODO, DEADLINE, EVENT -> addTask(command.getTask());
            case LIST -> ui.formatTaskList(tasks.getTasks());
            case MARK -> markTask(command.getTaskNumber());
            case UNMARK -> unmarkTask(command.getTaskNumber());
            case DELETE -> deleteTask(command.getTaskNumber());
            case UNDO -> undoLastTaskChange();
            case ON -> formatTasksOnDate(command.getDate());
            case FIND -> formatMatchingTasks(command.getKeyword());
            case BYE -> requestExit();
            case UNKNOWN -> throw new AssertionError("Parser returned an unknown command");
        };
    }

    /**
     * Adds a task, saves the updated task list, and formats the response.
     *
     * @param task Task to add.
     * @return Response describing the added task.
     * @throws KojisPawnException If the updated task list cannot be saved.
     */
    private String addTask(Task task) throws KojisPawnException {
        assert task != null : "Task creation commands must contain a task";

        TaskList previousTasks = tasks.copy();
        tasks.add(task);
        storage.save(tasks);
        undoSnapshot = previousTasks;
        return ui.formatTaskAdded(task, tasks.size());
    }

    /**
     * Marks a task, saves the updated task list, and formats the response.
     *
     * @param taskNumber One-based number of the task to mark.
     * @return Response describing the marked task.
     * @throws KojisPawnException If the task number is invalid or the task list cannot be saved.
     */
    private String markTask(Integer taskNumber) throws KojisPawnException {
        assert taskNumber != null && taskNumber > 0
                : "Mark commands must contain a positive task number";

        TaskList previousTasks = tasks.copy();
        Task markedTask = tasks.mark(taskNumber);
        storage.save(tasks);
        undoSnapshot = previousTasks;
        return ui.formatTaskMarked(markedTask);
    }

    /**
     * Unmarks a task, saves the updated task list, and formats the response.
     *
     * @param taskNumber One-based number of the task to unmark.
     * @return Response describing the unmarked task.
     * @throws KojisPawnException If the task number is invalid or the task list cannot be saved.
     */
    private String unmarkTask(Integer taskNumber) throws KojisPawnException {
        assert taskNumber != null && taskNumber > 0
                : "Unmark commands must contain a positive task number";

        TaskList previousTasks = tasks.copy();
        Task unmarkedTask = tasks.unmark(taskNumber);
        storage.save(tasks);
        undoSnapshot = previousTasks;
        return ui.formatTaskUnmarked(unmarkedTask);
    }

    /**
     * Deletes a task, saves the updated task list, and formats the response.
     *
     * @param taskNumber One-based number of the task to delete.
     * @return Response describing the deleted task.
     * @throws KojisPawnException If the task number is invalid or the task list cannot be saved.
     */
    private String deleteTask(Integer taskNumber) throws KojisPawnException {
        assert taskNumber != null && taskNumber > 0
                : "Delete commands must contain a positive task number";

        TaskList previousTasks = tasks.copy();
        Task deletedTask = tasks.delete(taskNumber);
        storage.save(tasks);
        undoSnapshot = previousTasks;
        return ui.formatTaskDeleted(deletedTask, tasks.size());
    }

    /**
     * Restores and saves the task state from before the most recent successful change.
     *
     * @return Response confirming the restored state.
     * @throws KojisPawnException If there is no change to undo or the restored state cannot be saved.
     */
    private String undoLastTaskChange() throws KojisPawnException {
        if (undoSnapshot == null) {
            throw new KojisPawnException("There is no task change to undo.");
        }

        tasks.replaceWith(undoSnapshot);
        storage.save(tasks);
        undoSnapshot = null;
        return ui.formatUndo();
    }

    /**
     * Finds tasks occurring on a date and formats the response.
     *
     * @param date Date to search for.
     * @return Response containing tasks that occur on the date.
     */
    private String formatTasksOnDate(LocalDate date) {
        assert date != null : "On commands must contain a date";

        return ui.formatTasksOnDate(tasks.findOn(date), date);
    }

    /**
     * Finds tasks matching a keyword and formats the response.
     *
     * @param keyword Keyword to find.
     * @return Response containing matching tasks.
     */
    private String formatMatchingTasks(String keyword) {
        assert keyword != null && !keyword.isBlank()
                : "Find commands must contain a keyword";

        return ui.formatMatchingTasks(tasks.find(keyword));
    }

    /**
     * Records that the application should exit and returns the farewell response.
     *
     * @return Farewell response.
     */
    private String requestExit() {
        isExitRequested = true;
        return ui.getExitMessage();
    }
}
