package kojispawn;

import java.nio.file.Path;

import kojispawn.command.Command;
import kojispawn.command.CommandType;
import kojispawn.command.Parser;
import kojispawn.exception.KojisPawnException;
import kojispawn.storage.Storage;
import kojispawn.task.Task;
import kojispawn.task.TaskList;
import kojispawn.ui.Ui;

/**
 * Coordinates input parsing, task management, and user interaction.
 */
public class KojisPawn {
    private final Parser parser;
    private final Storage storage;
    private final TaskList tasks;
    private final Ui ui;
    private CommandType lastCommandType = CommandType.UNKNOWN;
    private boolean isExitRequested;

    /**
     * Creates the chatbot and loads any tasks saved in the default data file.
     *
     * @throws KojisPawnException If the task data cannot be loaded.
     */
    public KojisPawn() throws KojisPawnException {
        this(Path.of("data", "kojispawn.txt"));
    }

    KojisPawn(Path dataFile) throws KojisPawnException {
        this.parser = new Parser();
        this.storage = new Storage(dataFile);
        this.tasks = new TaskList(storage.load());
        this.ui = new Ui();
    }

    /**
     * Starts Koji's Pawn.
     *
     * @param args Command-line arguments, which are not used.
     * @throws KojisPawnException If the task data cannot be loaded.
     */
    public static void main(String[] args) throws KojisPawnException {
        new KojisPawn().run();
    }

    /**
     * Runs the chatbot until the user enters the {@code bye} command.
     */
    public void run() {
        ui.showGreeting();
        while (!isExitRequested) {
            ui.showResponse(getResponse(ui.readCommand()));
        }

        ui.close();
    }

    /**
     * Parses and executes one command for either the console or GUI.
     *
     * @param input Command entered by the user.
     * @return Response generated by Koji's Pawn.
     */
    public String getResponse(String input) {
        try {
            Command command = parser.parse(input);
            lastCommandType = command.getType();
            return execute(command);
        } catch (KojisPawnException exception) {
            lastCommandType = CommandType.UNKNOWN;
            return exception.getMessage();
        }
    }

    /**
     * Returns the type of the most recently processed command.
     *
     * @return Most recent command type, or {@link CommandType#UNKNOWN} after an error.
     */
    public CommandType getLastCommandType() {
        return lastCommandType;
    }

    /**
     * Returns whether the user has entered the {@code bye} command.
     *
     * @return {@code true} when the application should exit.
     */
    public boolean isExitRequested() {
        return isExitRequested;
    }

    /**
     * Executes a validated command.
     *
     * @param command Command returned by the parser.
     * @return Response describing the result.
     * @throws KojisPawnException If a task number is outside the list.
     */
    private String execute(Command command) throws KojisPawnException {
        return switch (command.getType()) {
            case TODO, DEADLINE, EVENT:
                tasks.add(command.getTask());
                storage.save(tasks);
                yield ui.formatTaskAdded(command.getTask(), tasks.size());
            case LIST:
                yield ui.formatTaskList(tasks.getTasks());
            case MARK:
                Task markedTask = tasks.mark(command.getTaskNumber());
                storage.save(tasks);
                yield ui.formatTaskMarked(markedTask);
            case UNMARK:
                Task unmarkedTask = tasks.unmark(command.getTaskNumber());
                storage.save(tasks);
                yield ui.formatTaskUnmarked(unmarkedTask);
            case DELETE:
                Task deletedTask = tasks.delete(command.getTaskNumber());
                storage.save(tasks);
                yield ui.formatTaskDeleted(deletedTask, tasks.size());
            case ON:
                yield ui.formatTasksOnDate(tasks.findOn(command.getDate()), command.getDate());
            case FIND:
                yield ui.formatMatchingTasks(tasks.find(command.getKeyword()));
            case BYE:
                isExitRequested = true;
                yield ui.getExitMessage();
            case UNKNOWN:
                throw new AssertionError("Parser returned an unknown command");
        };
    }
}
